### ISSUE TITLE
Where to the latest data from?

### ISSUE THREAD

**Issue by whogopu** [nimitsolanki/IPL-2019#1]
Hey @nimitsolanki this is really a very helpful repo. I am also working on a side project which needs latest IPL data. Can you please tell me from where did you get this dataset.
Thanks.

**Comment by nimitsolanki** [comment]
Hi @gopal151295 , 

You can get the IPL data between 2008 to 2018 from the following Kaggle page: 
https://www.kaggle.com/nowke9/ipldata

Regards,
Nimit
